address: :8443
authenticate_service_url: https://authenticate.localhost.pomerium.io:8443
certificate_file: /pomerium/certs/pomerium-local.crt
certificate_key_file: /pomerium/certs/pomerium-local.key
cookie_secret: Y2FudGVyYnVyeS1sb2NhbC1jb29raWUtc2VjcmV0ISE=
idp_client_id: pomerium
idp_client_secret: pomerium-local-client-secret
idp_provider: oidc
idp_provider_url: http://dex.localhost.pomerium.io:5556/dex
idp_scopes: openid,profile,email
shared_secret: Y2FudGVyYnVyeS1sb2NhbC1zaGFyZWQtc2VjcmV0ISE=
signing_key_file: /pomerium/keys/pomerium-signing-key.pem

routes:
  - from: https://vault.localhost.pomerium.io
    to: http://vault-service:50051
    allow_any_authenticated_user: true
    bearer_token_format: idp_identity_token
    pass_identity_headers: true
    set_request_headers:
      Authorization: Bearer ${pomerium.jwt}
